export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_GET_ORDER: "WS_GET_ORDER" = "WS_GET_ORDER";
export const WS_SEND_ORDER: "WS_SEND_ORDER" = "WS_SEND_ORDER";
export const WS_DISCONNECT: "WS_DISCONNECT" = "WS_DISCONNECT";
