export const GET_CONSTRUCTOR_INGREDIENTS_REQUEST =
  "GET_CONSTRUCTOR_INGREDIENTS_REQUEST";
export const GET_CONSTRUCTOR_INGREDIENTS_FAIL =
  "GET_CONSTRUCTOR_INGREDIENTS_FAIL";
export const GET_CONSTRUCTOR_INGREDIENTS_SUCCESS =
  "GET_CONSTRUCTOR_INGREDIENTS_SUCCESS";
