export const GET_CONSTRUCTOR_INGREDIENTS_REQUEST =
  "GET_CONSTRUCTOR_INGREDIENTS_REQUEST";
export const GET_CONSTRUCTOR_INGREDIENTS_ERROR =
  "GET_CONSTRUCTOR_INGREDIENTS_ERROR";
export const GET_CONSTRUCTOR_INGREDIENTS_SUCCESS =
  "GET_CONSTRUCTOR_INGREDIENTS_SUCCESS";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const SET_CONSTRUCTOR_INGREDIENTS = "SET_CONSTRUCTOR_INGREDIENTS";
export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_CONSTRUCTOR_INGREDIENT";
export const REMOVE_CONSTRUCTOR_INGREDIENT = "REMOVE_CONSTRUCTOR_INGREDIENT";
export const MOVE_CONSTRUCTOR_INGREDIENT = "MOVE_CONSTRUCTOR_INGREDIENT";
