export const GET_CONSTRUCTOR_INGREDIENTS_REQUEST =
  "GET_CONSTRUCTOR_INGREDIENTS_REQUEST";
export const GET_CONSTRUCTOR_INGREDIENTS_FAIL =
  "GET_CONSTRUCTOR_INGREDIENTS_FAIL";
export const GET_CONSTRUCTOR_INGREDIENTS_SUCCESS =
  "GET_CONSTRUCTOR_INGREDIENTS_SUCCESS";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const SET_CONSTRUCTOR_INGREDIENTS = "SET_CONSTRUCTOR_INGREDIENTS";
export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_CONSTRUCTOR_INGREDIENT";
